siteTitle = "Jonas Clark Website"
siteDescr = "A personal website devoted to musings about tech."
siteAuthor = "Jonas Clark"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/jonasvclark"
siteGithubUrl = "https://github.com/JonasClark"
siteEmailUrl = "jonasvclark@gmail.com"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = "/lumen"
